version: "3.7"
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        links:
            - php
        ports: []
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        env_file: .env.test
        links:
            - mysql
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
